name: Deploy CDK Stack

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    env:
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
      GAME_SERVER_ENDPOINT: https://joelle-unreleasable-defeatedly.ngrok-free.dev
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install CDK app deps
        working-directory: ./cdk
        run: |
          npm ci

      - name: Build Lambdas
        run: |
          cd cdk/lambdas/test && npm install && npm run build
          cd ../reply && npm install && npm run build

      - name: Set STAGE
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if [[ "${{ github.base_ref }}" == "main" ]]; then
              echo "STAGE=prod" >> $GITHUB_ENV
            else
              echo "STAGE=dev" >> $GITHUB_ENV
            fi
          else
            # push イベントなら ref_name から直接取得（main→prod / dev→dev）
            if [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "STAGE=prod" >> $GITHUB_ENV
            else
              echo "STAGE=dev" >> $GITHUB_ENV
            fi
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: CDK Diff
        if: github.event_name == 'pull_request'
        working-directory: ./cdk
        run: |
          echo "STAGE: $STAGE"
          npx cdk diff --all || true

      - name: CDK Deploy
        if: github.event_name == 'push'
        id: deploy
        working-directory: ./cdk
        run: |
          echo "STAGE: $STAGE"
          npx cdk deploy --all --require-approval never --outputs-file cdk-outputs.json

      - name: Show CDK Outputs
        if: github.event_name == 'push'
        working-directory: ./cdk
        run: cat cdk-outputs.json
